---
application_namespace: "kubecloud-demo"
application_name: "nginx"
application_expected_replicas: 2

application_dev_kubeconfig: "/etc/rancher/k3s/k3s.yaml"
application_prod_kubeconfig: "/etc/kubernetes/admin.conf"
