---
application_namespace: "kubecloud-demo"

application_components:
  - name: frontend
    kind: deployment
    expected_replicas: 2

  - name: backend
    kind: deployment
    expected_replicas: 2

  - name: postgres
    kind: statefulset
    expected_replicas: 1

application_check_pvc: true
application_postgres_pvc_name: postgres-data
