all:
  children:

    management:
      hosts:
        kubecloud-mgmt:
          ansible_host: 10.31.136.150

    development:
      hosts:
        kubecloud-dev:
          ansible_host: 10.31.136.151

    production:
      hosts:
        kubecloud-prod:
          ansible_host: 10.31.136.152

    kubernetes:
      children:
        management:
        development:
        production:
