apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: kubecloud-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        kubecloud.io/config-version: "crud-v1"
    spec:
      containers:
        - name: frontend
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20

          volumeMounts:
            - name: frontend-files
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html

            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf

      volumes:
        - name: frontend-files
          configMap:
            name: kubecloud-demo-frontend-files

        - name: nginx-config
          configMap:
            name: kubecloud-demo-frontend-nginx
