apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: kubecloud-applications
  namespace: fleet-default
spec:
  repo: "https://github.com/Amine99x/ACS.git"
  branch: main

  paths:
    - fleet/applications

  targets:
    - name: development
      clusterSelector:
        matchLabels:
          environment: development

    - name: production
      clusterSelector:
        matchLabels:
          environment: production
