---
- name: Prepare KubeCloud controlled drift simulation
  hosts: management
  become: true

  environment:
    PATH: "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
    KUBECONFIG: "/etc/rancher/rke2/rke2.yaml"

  roles:
    - drift_simulation
